version: "3.4"

services:
  # server:
  #   container_name: api
  #   image: api
  #   build: ./
  #   command: ./app
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - pg_container

  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "api_service_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_EXTENSIONS: "uuid-ossp"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
